"""add layout column to report_definitions"""
from alembic import op
import sqlalchemy as sa


revision = 'f3e0618d2cd5'
down_revision = 'f931a9c38d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_definitions', sa.Column('layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_definitions', 'layout')
    # ### end Alembic commands ###