"""reports layering initial schema"""
from alembic import op
import sqlalchemy as sa


revision = 'f931a9c38d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('chart', sa.JSON(), nullable=True),
    sa.Column('output_types', sa.JSON(), nullable=False),
    sa.Column('access_groups', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_definitions_slug'), 'report_definitions', ['slug'], unique=True)
    op.create_table('report_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_groups_slug'), 'report_groups', ['slug'], unique=True)
    op.create_table('report_group_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['report_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_key', name='uq_group_user')
    )
    op.create_index(op.f('ix_report_group_memberships_group_id'), 'report_group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_report_group_memberships_user_key'), 'report_group_memberships', ['user_key'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('result_columns', sa.JSON(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=False),
    sa.Column('params_used', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_report_id'), 'report_snapshots', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_snapshots_run_at'), 'report_snapshots', ['run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_snapshots_run_at'), table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_report_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_report_group_memberships_user_key'), table_name='report_group_memberships')
    op.drop_index(op.f('ix_report_group_memberships_group_id'), table_name='report_group_memberships')
    op.drop_table('report_group_memberships')
    op.drop_index(op.f('ix_report_groups_slug'), table_name='report_groups')
    op.drop_table('report_groups')
    op.drop_index(op.f('ix_report_definitions_slug'), table_name='report_definitions')
    op.drop_table('report_definitions')
    op.drop_table('example_records')
    # ### end Alembic commands ###