"""add is_live and schedules to report_definitions"""
from alembic import op
import sqlalchemy as sa


revision = 'ff9b50d341e2'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_definitions', sa.Column('is_live', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('report_definitions', sa.Column('schedules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_definitions', 'schedules')
    op.drop_column('report_definitions', 'is_live')
    # ### end Alembic commands ###