"""initial lead-locator schema (PostGIS)

Revision ID: 0001_initial
Revises:
Create Date: Phase 2

Hand-written rather than autogenerated: the PostGIS extension has to exist
before any Geometry column is created, and autogenerate does not know that.
GeoAlchemy2 also emits its own spatial indexes implicitly, so every Geometry
column here is declared spatial_index=False in the model and indexed
explicitly below — otherwise the index gets created twice and the migration
fails on the duplicate.
"""

from __future__ import annotations

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # Scaffold placeholder model. It ships with no migration of its own, which
    # leaves autogenerate permanently dirty; created here so drift checks mean
    # something. Drop it once the generated sample endpoints are replaced.
    op.create_table(
        "example_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "lead_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("query_raw", sa.String(length=255), nullable=False),
        sa.Column("query_kind", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("state_fips", sa.String(length=2), nullable=True),
        sa.Column("county_fips", sa.String(length=3), nullable=True),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column(
            "bbox",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column(
            "center",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column("h3_resolution", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cell_count", sa.Integer(), nullable=True),
        sa.Column("poi_count", sa.Integer(), nullable=True),
        sa.Column("requested_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "h3_resolution BETWEEN 5 AND 11", name="ck_lead_searches_h3_resolution"
        ),
        sa.CheckConstraint(
            "status IN ('pending','scoring','complete','failed')",
            name="ck_lead_searches_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lead_searches_created_at", "lead_searches", ["created_at"])
    op.create_index("ix_lead_searches_status", "lead_searches", ["status"])
    op.create_index("ix_lead_searches_requested_by", "lead_searches", ["requested_by"])

    op.create_table(
        "pois",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.dialects.postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", name="uq_pois_source_id"),
    )
    op.create_index("ix_pois_category", "pois", ["category"])
    op.create_index("ix_pois_geometry", "pois", ["geometry"], postgresql_using="gist")
    op.create_index("ix_pois_category_geometry", "pois", ["category", "geometry"])

    op.create_table(
        "census_tracts",
        sa.Column("geoid", sa.String(length=11), nullable=False),
        sa.Column("state_fips", sa.String(length=2), nullable=False),
        sa.Column("county_fips", sa.String(length=3), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("median_household_income", sa.Integer(), nullable=True),
        sa.Column("households", sa.Integer(), nullable=True),
        sa.Column("area_land_sq_m", sa.BigInteger(), nullable=True),
        sa.Column("acs_year", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("geoid"),
    )
    op.create_index("ix_census_tracts_state_fips", "census_tracts", ["state_fips"])
    op.create_index(
        "ix_census_tracts_state_county", "census_tracts", ["state_fips", "county_fips"]
    )
    op.create_index(
        "ix_census_tracts_geometry",
        "census_tracts",
        ["geometry"],
        postgresql_using="gist",
    )

    op.create_table(
        "hex_cells",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("h3_index", sa.String(length=20), nullable=False),
        sa.Column("resolution", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON", srid=4326, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("traffic_proxy", sa.Float(), nullable=False),
        sa.Column("demand", sa.Float(), nullable=False),
        sa.Column("saturation", sa.Float(), nullable=False),
        sa.Column("anchor_pull", sa.Float(), nullable=False),
        sa.Column(
            "score_breakdown",
            sa.dialects.postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["search_id"], ["lead_searches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("search_id", "h3_index", name="uq_hex_cells_search_h3"),
    )
    op.create_index("ix_hex_cells_search_score", "hex_cells", ["search_id", "score"])
    op.create_index("ix_hex_cells_search_rank", "hex_cells", ["search_id", "rank"])
    op.create_index(
        "ix_hex_cells_geometry", "hex_cells", ["geometry"], postgresql_using="gist"
    )


def downgrade() -> None:
    op.drop_table("hex_cells")
    op.drop_table("census_tracts")
    op.drop_table("pois")
    op.drop_table("lead_searches")
    op.drop_table("example_records")
    # The postgis extension is intentionally left installed: other schemas in
    # the same database may depend on it, and dropping it would cascade.
